spring:
  application:
    name: eureka_server
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
logging:
  level:
    com.furqon.eureka: OFF
    com.furqon.discovery: OFF